/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularze;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcin
 */
public class FormDodajEdytujMagazyn extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    boolean czy_edycja = false; // zmienna potrzebna do wyboru zapytania SQL INSERT czy UPDATE
    Connection con;
    JTable jt;

    /**
     * Creates new form FormDodajEdytujMagazyn
     */
    public FormDodajEdytujMagazyn(Connection conn) { // konstruktor do dodawania magazynu
        con = conn;
        initComponents();
        wypelnijWoj();
        textStopkaL.setText(KonfiguracjaSystemu.getWersja());
        this.setLocationRelativeTo(null);
    }

    public FormDodajEdytujMagazyn() {
        initComponents();
        wypelnijWoj();
        textStopkaL.setText(KonfiguracjaSystemu.getWersja());
        this.setLocationRelativeTo(null);
    }

    public FormDodajEdytujMagazyn(Connection conn, JTable jt_) { // konstruktor do edycji magazynu
        con = conn;
        jt = jt_;
        czy_edycja = true;
        initComponents();
        wypelnijWoj();
        wypelnijDoEdycji();
        ustawNaglowekPrzycisk();
        textStopkaL.setText(KonfiguracjaSystemu.getWersja());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientNaglowek = new keeptoo.KGradientPanel();
        textWyjscie = new javax.swing.JLabel();
        textMinimalizuj = new javax.swing.JLabel();
        textNaglowek = new javax.swing.JLabel();
        gradientStopka = new keeptoo.KGradientPanel();
        textStopkaL = new javax.swing.JLabel();
        textStopkaP = new javax.swing.JLabel();
        gradientGlowny = new keeptoo.KGradientPanel();
        textNazwa = new javax.swing.JLabel();
        poleNazwa = new javax.swing.JTextField();
        textUlica = new javax.swing.JLabel();
        poleUlica = new javax.swing.JTextField();
        textMiasto = new javax.swing.JLabel();
        poleMiasto = new javax.swing.JTextField();
        textWojewodztwo = new javax.swing.JLabel();
        poleWyborWojewodztwo = new javax.swing.JComboBox<>();
        textKodPoczt = new javax.swing.JLabel();
        poleKodPoczt = new javax.swing.JTextField();
        przyciskDodaj = new javax.swing.JButton();
        przyciskAnuluj = new javax.swing.JButton();
        textId = new javax.swing.JLabel();
        textId2 = new javax.swing.JLabel();
        textSektor1 = new javax.swing.JLabel();
        poleSektor1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientNaglowek.setkEndColor(new java.awt.Color(65, 131, 215));
        gradientNaglowek.setkGradientFocus(600);
        gradientNaglowek.setkStartColor(new java.awt.Color(58, 83, 155));
        gradientNaglowek.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                gradientNaglowekMouseDragged(evt);
            }
        });
        gradientNaglowek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gradientNaglowekMousePressed(evt);
            }
        });

        textWyjscie.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        textWyjscie.setForeground(new java.awt.Color(255, 255, 255));
        textWyjscie.setText("X");
        textWyjscie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textWyjscie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textWyjscieMouseClicked(evt);
            }
        });

        textMinimalizuj.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textMinimalizuj.setForeground(new java.awt.Color(255, 255, 255));
        textMinimalizuj.setText("-");
        textMinimalizuj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textMinimalizuj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMinimalizujMouseClicked(evt);
            }
        });

        textNaglowek.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textNaglowek.setForeground(new java.awt.Color(255, 255, 255));
        textNaglowek.setText("DODAWANIE MAGAZYNU");

        javax.swing.GroupLayout gradientNaglowekLayout = new javax.swing.GroupLayout(gradientNaglowek);
        gradientNaglowek.setLayout(gradientNaglowekLayout);
        gradientNaglowekLayout.setHorizontalGroup(
            gradientNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientNaglowekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNaglowek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(textMinimalizuj, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textWyjscie)
                .addGap(21, 21, 21))
        );
        gradientNaglowekLayout.setVerticalGroup(
            gradientNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientNaglowekLayout.createSequentialGroup()
                .addGroup(gradientNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWyjscie)
                    .addComponent(textMinimalizuj, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNaglowek))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(gradientNaglowek, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 50));

        gradientStopka.setkEndColor(new java.awt.Color(98, 98, 98));
        gradientStopka.setkGradientFocus(600);
        gradientStopka.setkStartColor(new java.awt.Color(41, 59, 76));

        textStopkaL.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textStopkaL.setForeground(new java.awt.Color(255, 255, 255));
        textStopkaL.setText(" ver. 1.0.0");
        textStopkaL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textStopkaP.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textStopkaP.setForeground(new java.awt.Color(255, 255, 255));
        textStopkaP.setText("Copyright © Projekt i kodowanie: Marcin Kos");
        textStopkaP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout gradientStopkaLayout = new javax.swing.GroupLayout(gradientStopka);
        gradientStopka.setLayout(gradientStopkaLayout);
        gradientStopkaLayout.setHorizontalGroup(
            gradientStopkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientStopkaLayout.createSequentialGroup()
                .addComponent(textStopkaL, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textStopkaP, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        gradientStopkaLayout.setVerticalGroup(
            gradientStopkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textStopkaL, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
            .addComponent(textStopkaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(gradientStopka, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 460, 20));

        gradientGlowny.setkEndColor(new java.awt.Color(44, 62, 80));
        gradientGlowny.setkStartColor(new java.awt.Color(44, 62, 80));

        textNazwa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textNazwa.setForeground(new java.awt.Color(255, 255, 255));
        textNazwa.setText("Nazwa:");

        poleNazwa.setBackground(new java.awt.Color(108, 122, 137));
        poleNazwa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        poleNazwa.setForeground(new java.awt.Color(255, 255, 255));
        poleNazwa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        textUlica.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textUlica.setForeground(new java.awt.Color(255, 255, 255));
        textUlica.setText(" Ulica:");

        poleUlica.setBackground(new java.awt.Color(108, 122, 137));
        poleUlica.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        poleUlica.setForeground(new java.awt.Color(255, 255, 255));
        poleUlica.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        textMiasto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textMiasto.setForeground(new java.awt.Color(255, 255, 255));
        textMiasto.setText("Miasto:");

        poleMiasto.setBackground(new java.awt.Color(108, 122, 137));
        poleMiasto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        poleMiasto.setForeground(new java.awt.Color(255, 255, 255));
        poleMiasto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        textWojewodztwo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textWojewodztwo.setForeground(new java.awt.Color(255, 255, 255));
        textWojewodztwo.setText("Województwo:");

        poleWyborWojewodztwo.setBackground(new java.awt.Color(108, 122, 137));
        poleWyborWojewodztwo.setForeground(new java.awt.Color(108, 122, 137));

        textKodPoczt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textKodPoczt.setForeground(new java.awt.Color(255, 255, 255));
        textKodPoczt.setText("Kod pocztowy:");

        poleKodPoczt.setBackground(new java.awt.Color(108, 122, 137));
        poleKodPoczt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        poleKodPoczt.setForeground(new java.awt.Color(255, 255, 255));
        poleKodPoczt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        przyciskDodaj.setBackground(new java.awt.Color(75, 119, 190));
        przyciskDodaj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        przyciskDodaj.setForeground(new java.awt.Color(255, 255, 255));
        przyciskDodaj.setText("Dodaj");
        przyciskDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskDodajActionPerformed(evt);
            }
        });

        przyciskAnuluj.setBackground(new java.awt.Color(246, 71, 71));
        przyciskAnuluj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        przyciskAnuluj.setForeground(new java.awt.Color(255, 255, 255));
        przyciskAnuluj.setText("Anuluj");
        przyciskAnuluj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                przyciskAnulujMouseClicked(evt);
            }
        });

        textId.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textId.setForeground(new java.awt.Color(255, 255, 255));

        textId2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textId2.setForeground(new java.awt.Color(255, 255, 255));

        textSektor1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textSektor1.setForeground(new java.awt.Color(255, 255, 255));
        textSektor1.setText("Ilość sektorów:");

        poleSektor1.setBackground(new java.awt.Color(108, 122, 137));
        poleSektor1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        poleSektor1.setForeground(new java.awt.Color(255, 255, 255));
        poleSektor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        javax.swing.GroupLayout gradientGlownyLayout = new javax.swing.GroupLayout(gradientGlowny);
        gradientGlowny.setLayout(gradientGlownyLayout);
        gradientGlownyLayout.setHorizontalGroup(
            gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientGlownyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textId2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(gradientGlownyLayout.createSequentialGroup()
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gradientGlownyLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textSektor1)
                            .addComponent(textWojewodztwo))
                        .addGap(24, 24, 24)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleWyborWojewodztwo, 0, 200, Short.MAX_VALUE)
                            .addComponent(poleSektor1)))
                    .addGroup(gradientGlownyLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNazwa)
                            .addComponent(textUlica)
                            .addComponent(textMiasto)
                            .addComponent(textKodPoczt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(poleMiasto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(poleUlica, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleNazwa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleKodPoczt))))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientGlownyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(przyciskDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(przyciskAnuluj)
                .addGap(101, 101, 101))
        );
        gradientGlownyLayout.setVerticalGroup(
            gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientGlownyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textId)
                    .addComponent(textId2))
                .addGap(18, 18, 18)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNazwa)
                    .addComponent(poleNazwa, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUlica)
                    .addComponent(poleUlica, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poleMiasto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMiasto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKodPoczt)
                    .addComponent(poleKodPoczt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWojewodztwo)
                    .addComponent(poleWyborWojewodztwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSektor1)
                    .addComponent(poleSektor1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przyciskDodaj)
                    .addComponent(przyciskAnuluj))
                .addGap(151, 151, 151))
        );

        getContentPane().add(gradientGlowny, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textWyjscieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textWyjscieMouseClicked
        this.setVisible(false);
        FormGlowny.setEdycjaOtwarta(false);
    }//GEN-LAST:event_textWyjscieMouseClicked

    private void textMinimalizujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMinimalizujMouseClicked
        this.setState(FormDodajEdytujProdukt.ICONIFIED);
    }//GEN-LAST:event_textMinimalizujMouseClicked

    private void gradientNaglowekMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradientNaglowekMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_gradientNaglowekMouseDragged

    private void gradientNaglowekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradientNaglowekMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_gradientNaglowekMousePressed

    private void przyciskDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskDodajActionPerformed

        String id = textId.getText();
        String nazwa = poleNazwa.getText();
        String ulica = poleUlica.getText();
        String miasto = poleMiasto.getText();
        String kod_poczt = poleKodPoczt.getText();
        String wojewodztwo = poleWyborWojewodztwo.getSelectedItem().toString();
        String sektory = poleSektor1.getText();

        // Walidacja danych
        //nazwa
        String bledy = "";
        WalidatorDanych WL = new WalidatorDanych();

        WL.sprawdz("Nazwa", nazwa, 4, 45);
        WL.sprawdz("Ulica", ulica, 4, 45);
        WL.sprawdz("Miasto", miasto, 3, 45);
        WL.sprawdz("Kod Pocztowy", kod_poczt, 6, 6);
        WL.sprawdz("Sektor", sektory, 1, 45);

        bledy += WL.getZnalezioneBledy();

        // sprawdzanie czy wystapily bledy
        if (!bledy.equals("")) {
            JOptionPane.showMessageDialog(this, bledy, "Błąd!", 2);
            WL.usunBledy();
        }

        if (bledy.equals("")) { // walidacja poprawna
            PreparedStatement dodajm = null;
            PreparedStatement pobwoj;
            ResultSet wynikwoj;
            try {
                con.setAutoCommit(false);

                String query3 = "SELECT kod_w FROM wojewodztwa WHERE wojewodztwo='" + wojewodztwo + "'";
                pobwoj = con.prepareStatement(query3);
                wynikwoj = pobwoj.executeQuery(query3);
                wynikwoj.next();
                String tmp = wynikwoj.getString(1);
                //System.out.println("TEST id_t " + tmp2);

                //System.out.println("TEST id_d " + tmp3);
                String query1 = "INSERT INTO magazyny(id_m,nazwa, ulica, miasto, kod_pocztowy, ilosc_sektorow, kod_w) VALUES (NULL,?,?,?,?,?,?)";
                String query2 = "UPDATE magazyny SET nazwa=?, ulica=?, miasto=?, kod_pocztowy=?, ilosc_sektorow=?, kod_w=? WHERE id_m=?";

                if (czy_edycja) {
                    dodajm = con.prepareStatement(query2);
                    dodajm.setInt(7, Integer.parseInt(id));
                }

                if (!czy_edycja) {
                    dodajm = con.prepareStatement(query1);
                }

                dodajm.setString(1, nazwa);
                dodajm.setString(2, ulica);
                dodajm.setString(3, miasto);
                dodajm.setString(4, kod_poczt);
                dodajm.setString(5, sektory);
                dodajm.setString(6, tmp);

                dodajm.executeUpdate();

                con.commit();

                this.setVisible(false);
                FormGlowny.setEdycjaOtwarta(false);

            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(this, "Wprowadzone dane sa bledne!", "Błąd!", 2);
            }
        }
    }//GEN-LAST:event_przyciskDodajActionPerformed

    private void przyciskAnulujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_przyciskAnulujMouseClicked
        poleNazwa.setText("");
        poleUlica.setText("");
        poleMiasto.setText("");
        poleKodPoczt.setText("");
        poleSektor1.setText("");
        poleWyborWojewodztwo.setSelectedIndex(0);

    }//GEN-LAST:event_przyciskAnulujMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDodajEdytujMagazyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDodajEdytujMagazyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDodajEdytujMagazyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDodajEdytujMagazyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDodajEdytujMagazyn().setVisible(true);
            }
        });
    }

    public void wypelnijDoEdycji() {

        DefaultTableModel model = (DefaultTableModel) jt.getModel();
        int wiersz = jt.getSelectedRow();

        textId2.setText("ID: ");
        textId.setText(model.getValueAt(wiersz, 0).toString());
        poleNazwa.setText(model.getValueAt(wiersz, 1).toString());
        poleUlica.setText(model.getValueAt(wiersz, 2).toString());
        poleMiasto.setText(model.getValueAt(wiersz, 3).toString());
        poleWyborWojewodztwo.setSelectedItem(model.getValueAt(wiersz, 4).toString());
        poleKodPoczt.setText(model.getValueAt(wiersz, 5).toString());
        poleSektor1.setText(model.getValueAt(wiersz, 6).toString());

    }

    public void wypelnijWoj() {
        try {
            PreparedStatement pobierzWoj;
            ResultSet wynikWoj;
            String query = "SELECT wojewodztwo FROM wojewodztwa";

            pobierzWoj = con.prepareStatement(query);
            wynikWoj = pobierzWoj.executeQuery(query);

            while (wynikWoj.next()) {
                poleWyborWojewodztwo.addItem(wynikWoj.getString(1));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, "Błąd!", 2);
        }
    }

    public void ustawNaglowekPrzycisk() {
        textNaglowek.setText("EDYTOWANIE MAGAZYNU");
        przyciskDodaj.setText("Edytuj");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel gradientGlowny;
    private keeptoo.KGradientPanel gradientNaglowek;
    private keeptoo.KGradientPanel gradientStopka;
    private javax.swing.JTextField poleKodPoczt;
    private javax.swing.JTextField poleMiasto;
    private javax.swing.JTextField poleNazwa;
    private javax.swing.JTextField poleSektor1;
    private javax.swing.JTextField poleUlica;
    private javax.swing.JComboBox<String> poleWyborWojewodztwo;
    private javax.swing.JButton przyciskAnuluj;
    private javax.swing.JButton przyciskDodaj;
    private javax.swing.JLabel textId;
    private javax.swing.JLabel textId2;
    private javax.swing.JLabel textKodPoczt;
    private javax.swing.JLabel textMiasto;
    private javax.swing.JLabel textMinimalizuj;
    private javax.swing.JLabel textNaglowek;
    private javax.swing.JLabel textNazwa;
    private javax.swing.JLabel textSektor1;
    private javax.swing.JLabel textStopkaL;
    private javax.swing.JLabel textStopkaP;
    private javax.swing.JLabel textUlica;
    private javax.swing.JLabel textWojewodztwo;
    private javax.swing.JLabel textWyjscie;
    // End of variables declaration//GEN-END:variables
}
