/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularze;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcin
 */
public class FormKonfiguracjaSys extends javax.swing.JFrame {
    
    private int xMouse;
    private int yMouse;
    private static Connection con;
    private static KonfiguracjaSystemu KS;
    private static FormGlowny FG;

    /**
     * Creates new form FormKonfiguracjaSys
     */
    public FormKonfiguracjaSys(Connection con, KonfiguracjaSystemu KS, FormGlowny FG) {
        this.con = con;
        initComponents();
        this.KS = KS;
        this.FG = FG;
        uzupelnijPola();
        this.setLocationRelativeTo(null);
    }
    
    public FormKonfiguracjaSys() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientNaglowek = new keeptoo.KGradientPanel();
        textWyjscie = new javax.swing.JLabel();
        textMinimalizuj = new javax.swing.JLabel();
        textNaglowek = new javax.swing.JLabel();
        gradientGlowny = new keeptoo.KGradientPanel();
        textNazwaSkrot = new javax.swing.JLabel();
        textNazwaSys = new javax.swing.JLabel();
        pAktualizuj = new javax.swing.JButton();
        przyciskAnuluj = new javax.swing.JButton();
        textNazwaFirmy = new javax.swing.JLabel();
        textWersjaSys = new javax.swing.JLabel();
        textOgloszenie = new javax.swing.JLabel();
        poleOgloszenie = new javax.swing.JTextArea();
        pWlWylOglosz = new javax.swing.JCheckBox();
        poleNazwaFirmy = new javax.swing.JTextField();
        poleNazwaSys = new javax.swing.JTextField();
        poleWersjaSys = new javax.swing.JTextField();
        poleNazwaSkrot = new javax.swing.JTextField();
        textWWW = new javax.swing.JLabel();
        poleWWW = new javax.swing.JTextField();
        textWiadPowitalna = new javax.swing.JLabel();
        poleWiadPowitalna = new javax.swing.JTextArea();
        maxZnaki = new javax.swing.JLabel();
        maxZnaki1 = new javax.swing.JLabel();
        gradientStopka = new keeptoo.KGradientPanel();
        textStopkaL = new javax.swing.JLabel();
        textStopkaP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientNaglowek.setkEndColor(new java.awt.Color(65, 131, 215));
        gradientNaglowek.setkGradientFocus(600);
        gradientNaglowek.setkStartColor(new java.awt.Color(58, 83, 155));
        gradientNaglowek.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                gradientNaglowekMouseDragged(evt);
            }
        });
        gradientNaglowek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gradientNaglowekMousePressed(evt);
            }
        });

        textWyjscie.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        textWyjscie.setForeground(new java.awt.Color(255, 255, 255));
        textWyjscie.setText("X");
        textWyjscie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textWyjscie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textWyjscieMouseClicked(evt);
            }
        });

        textMinimalizuj.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textMinimalizuj.setForeground(new java.awt.Color(255, 255, 255));
        textMinimalizuj.setText("-");
        textMinimalizuj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textMinimalizuj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMinimalizujMouseClicked(evt);
            }
        });

        textNaglowek.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textNaglowek.setForeground(new java.awt.Color(255, 255, 255));
        textNaglowek.setText("KONFIGURACJA SYSTEMU");

        javax.swing.GroupLayout gradientNaglowekLayout = new javax.swing.GroupLayout(gradientNaglowek);
        gradientNaglowek.setLayout(gradientNaglowekLayout);
        gradientNaglowekLayout.setHorizontalGroup(
            gradientNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientNaglowekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNaglowek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(textMinimalizuj, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textWyjscie)
                .addGap(21, 21, 21))
        );
        gradientNaglowekLayout.setVerticalGroup(
            gradientNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientNaglowekLayout.createSequentialGroup()
                .addGroup(gradientNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWyjscie)
                    .addComponent(textMinimalizuj, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNaglowek))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(gradientNaglowek, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        gradientGlowny.setkEndColor(new java.awt.Color(44, 62, 80));
        gradientGlowny.setkStartColor(new java.awt.Color(44, 62, 80));

        textNazwaSkrot.setBackground(new java.awt.Color(65, 131, 215));
        textNazwaSkrot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textNazwaSkrot.setForeground(new java.awt.Color(105, 163, 237));
        textNazwaSkrot.setText("Nazwa skrócona:");

        textNazwaSys.setBackground(new java.awt.Color(65, 131, 215));
        textNazwaSys.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textNazwaSys.setForeground(new java.awt.Color(105, 163, 237));
        textNazwaSys.setText("Nazwa systemu:");

        pAktualizuj.setBackground(new java.awt.Color(75, 119, 190));
        pAktualizuj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pAktualizuj.setForeground(new java.awt.Color(255, 255, 255));
        pAktualizuj.setText("Aktualizuj");
        pAktualizuj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAktualizujMouseClicked(evt);
            }
        });

        przyciskAnuluj.setBackground(new java.awt.Color(246, 71, 71));
        przyciskAnuluj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        przyciskAnuluj.setForeground(new java.awt.Color(255, 255, 255));
        przyciskAnuluj.setText("Anuluj");
        przyciskAnuluj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                przyciskAnulujMouseClicked(evt);
            }
        });

        textNazwaFirmy.setBackground(new java.awt.Color(65, 131, 215));
        textNazwaFirmy.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textNazwaFirmy.setForeground(new java.awt.Color(105, 163, 237));
        textNazwaFirmy.setText("Nazwa firmy:");

        textWersjaSys.setBackground(new java.awt.Color(65, 131, 215));
        textWersjaSys.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textWersjaSys.setForeground(new java.awt.Color(105, 163, 237));
        textWersjaSys.setText("Wersja systemu:");

        textOgloszenie.setBackground(new java.awt.Color(65, 131, 215));
        textOgloszenie.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textOgloszenie.setForeground(new java.awt.Color(105, 163, 237));
        textOgloszenie.setText("Ogloszenie:");

        poleOgloszenie.setBackground(new java.awt.Color(108, 122, 137));
        poleOgloszenie.setColumns(20);
        poleOgloszenie.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poleOgloszenie.setForeground(new java.awt.Color(255, 255, 255));
        poleOgloszenie.setLineWrap(true);
        poleOgloszenie.setRows(5);
        poleOgloszenie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        poleOgloszenie.setMargin(new java.awt.Insets(1, 1, 1, 1));
        poleOgloszenie.setMaximumSize(null);
        poleOgloszenie.setPreferredSize(null);

        pWlWylOglosz.setForeground(new java.awt.Color(255, 255, 255));
        pWlWylOglosz.setText("Włącz / Wyłącz");

        poleNazwaFirmy.setBackground(new java.awt.Color(108, 122, 137));
        poleNazwaFirmy.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poleNazwaFirmy.setForeground(new java.awt.Color(255, 255, 255));
        poleNazwaFirmy.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        poleNazwaSys.setBackground(new java.awt.Color(108, 122, 137));
        poleNazwaSys.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poleNazwaSys.setForeground(new java.awt.Color(255, 255, 255));
        poleNazwaSys.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        poleWersjaSys.setBackground(new java.awt.Color(108, 122, 137));
        poleWersjaSys.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poleWersjaSys.setForeground(new java.awt.Color(255, 255, 255));
        poleWersjaSys.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        poleNazwaSkrot.setBackground(new java.awt.Color(108, 122, 137));
        poleNazwaSkrot.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poleNazwaSkrot.setForeground(new java.awt.Color(255, 255, 255));
        poleNazwaSkrot.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        textWWW.setBackground(new java.awt.Color(65, 131, 215));
        textWWW.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textWWW.setForeground(new java.awt.Color(105, 163, 237));
        textWWW.setText("Strona www:");

        poleWWW.setBackground(new java.awt.Color(108, 122, 137));
        poleWWW.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poleWWW.setForeground(new java.awt.Color(255, 255, 255));
        poleWWW.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        textWiadPowitalna.setBackground(new java.awt.Color(65, 131, 215));
        textWiadPowitalna.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textWiadPowitalna.setForeground(new java.awt.Color(105, 163, 237));
        textWiadPowitalna.setText("<html><center>Wiadomość<br>powitalna:</center></html>");

        poleWiadPowitalna.setBackground(new java.awt.Color(108, 122, 137));
        poleWiadPowitalna.setColumns(20);
        poleWiadPowitalna.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poleWiadPowitalna.setForeground(new java.awt.Color(255, 255, 255));
        poleWiadPowitalna.setLineWrap(true);
        poleWiadPowitalna.setRows(5);
        poleWiadPowitalna.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        poleWiadPowitalna.setMargin(new java.awt.Insets(1, 1, 1, 1));
        poleWiadPowitalna.setMaximumSize(null);
        poleWiadPowitalna.setPreferredSize(null);

        maxZnaki.setForeground(new java.awt.Color(255, 255, 255));
        maxZnaki.setText("Max. 200 znaków");

        maxZnaki1.setForeground(new java.awt.Color(255, 255, 255));
        maxZnaki1.setText("Max. 400 znaków");

        javax.swing.GroupLayout gradientGlownyLayout = new javax.swing.GroupLayout(gradientGlowny);
        gradientGlowny.setLayout(gradientGlownyLayout);
        gradientGlownyLayout.setHorizontalGroup(
            gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientGlownyLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientGlownyLayout.createSequentialGroup()
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNazwaSys)
                            .addComponent(textNazwaSkrot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleNazwaSys, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poleNazwaSkrot, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gradientGlownyLayout.createSequentialGroup()
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textWersjaSys)
                            .addComponent(textNazwaFirmy)
                            .addComponent(textWWW)
                            .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textWiadPowitalna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textOgloszenie)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradientGlownyLayout.createSequentialGroup()
                                .addComponent(poleWiadPowitalna, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maxZnaki1))
                            .addGroup(gradientGlownyLayout.createSequentialGroup()
                                .addComponent(poleOgloszenie, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pWlWylOglosz)
                                    .addComponent(maxZnaki)))
                            .addComponent(poleNazwaFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poleWersjaSys, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poleWWW, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientGlownyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pAktualizuj)
                .addGap(18, 18, 18)
                .addComponent(przyciskAnuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        gradientGlownyLayout.setVerticalGroup(
            gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientGlownyLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNazwaSys)
                    .addComponent(poleNazwaSys, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNazwaSkrot)
                    .addComponent(poleNazwaSkrot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNazwaFirmy)
                    .addComponent(poleNazwaFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWersjaSys)
                    .addComponent(poleWersjaSys, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWWW)
                    .addComponent(poleWWW, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gradientGlownyLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(textOgloszenie))
                    .addGroup(gradientGlownyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(poleOgloszenie, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradientGlownyLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(pWlWylOglosz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxZnaki)))
                .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientGlownyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleWiadPowitalna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(gradientGlownyLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(maxZnaki1)))
                        .addGap(18, 18, 18)
                        .addGroup(gradientGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(przyciskAnuluj)
                            .addComponent(pAktualizuj))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientGlownyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(textWiadPowitalna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
        );

        getContentPane().add(gradientGlowny, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 670, 510));

        gradientStopka.setkEndColor(new java.awt.Color(98, 98, 98));
        gradientStopka.setkGradientFocus(600);
        gradientStopka.setkStartColor(new java.awt.Color(41, 59, 76));

        textStopkaL.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textStopkaL.setForeground(new java.awt.Color(255, 255, 255));
        textStopkaL.setText(" ver. 1.0.0");
        textStopkaL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textStopkaP.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textStopkaP.setForeground(new java.awt.Color(255, 255, 255));
        textStopkaP.setText("Copyright © Projekt i kodowanie: Marcin Kos");
        textStopkaP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout gradientStopkaLayout = new javax.swing.GroupLayout(gradientStopka);
        gradientStopka.setLayout(gradientStopkaLayout);
        gradientStopkaLayout.setHorizontalGroup(
            gradientStopkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientStopkaLayout.createSequentialGroup()
                .addComponent(textStopkaL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(textStopkaP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        gradientStopkaLayout.setVerticalGroup(
            gradientStopkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientStopkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textStopkaL, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addComponent(textStopkaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(gradientStopka, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 670, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textWyjscieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textWyjscieMouseClicked
        this.setVisible(false);
        FormGlowny.setEdycjaOtwarta(false);
    }//GEN-LAST:event_textWyjscieMouseClicked

    private void textMinimalizujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMinimalizujMouseClicked
        this.setState(FormDodajEdytujProdukt.ICONIFIED);
    }//GEN-LAST:event_textMinimalizujMouseClicked

    private void gradientNaglowekMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradientNaglowekMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_gradientNaglowekMouseDragged

    private void gradientNaglowekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradientNaglowekMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_gradientNaglowekMousePressed

    private void pAktualizujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAktualizujMouseClicked
        Object[] opcje = {"Tak", "Nie"};
        int czy_napewno = JOptionPane.showOptionDialog(this, "Czy napewno chcesz zmienić konfiguracje?", "Zmiana konfiguracji", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcje, opcje[0]);
        
        if (czy_napewno == 0) {
            KS.setNazwa(poleNazwaSys.getText());
            KS.setNazwa_skrot(poleNazwaSkrot.getText());
            KS.setNazwa_firmy(poleNazwaFirmy.getText());
            KS.setWersja(poleWersjaSys.getText());
            if (pWlWylOglosz.isSelected()) {
                KS.setOgloszenie(1);
            } else {
                KS.setOgloszenie(0);
            }
            KS.setOgloszenie_tekst(poleOgloszenie.getText());
            KS.setStronaWWW(poleWWW.getText());
            KS.setWiadomosc_powitalna(poleWiadPowitalna.getText());
            KS.aktualizujDane();
            FG.pokaz_statystyki_admin();
            this.dispose();
            
        }
    }//GEN-LAST:event_pAktualizujMouseClicked

    private void przyciskAnulujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_przyciskAnulujMouseClicked
        uzupelnijPola();
    }//GEN-LAST:event_przyciskAnulujMouseClicked
    
    private void uzupelnijPola() {
        textStopkaL.setText(KonfiguracjaSystemu.getWersja());
        poleNazwaSys.setText(KS.getNazwa());
        poleNazwaSkrot.setText(KS.getNazwa_skrot());
        poleNazwaFirmy.setText(KS.getNazwa_firmy());
        poleWersjaSys.setText(KS.getWersja());
        poleWWW.setText(KS.getStronaWWW());
        if (KS.getOgloszenie() == 1) {
            pWlWylOglosz.setSelected(true);
        } else {
            pWlWylOglosz.setSelected(false);
        }
        poleOgloszenie.setText(KS.getOgloszenie_tekst());
        poleWiadPowitalna.setText(KS.getWiadomosc_powitalna());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKonfiguracjaSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKonfiguracjaSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKonfiguracjaSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKonfiguracjaSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKonfiguracjaSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel gradientGlowny;
    private keeptoo.KGradientPanel gradientNaglowek;
    private keeptoo.KGradientPanel gradientStopka;
    private javax.swing.JLabel maxZnaki;
    private javax.swing.JLabel maxZnaki1;
    private javax.swing.JButton pAktualizuj;
    private javax.swing.JCheckBox pWlWylOglosz;
    private javax.swing.JTextField poleNazwaFirmy;
    private javax.swing.JTextField poleNazwaSkrot;
    private javax.swing.JTextField poleNazwaSys;
    private javax.swing.JTextArea poleOgloszenie;
    private javax.swing.JTextField poleWWW;
    private javax.swing.JTextField poleWersjaSys;
    private javax.swing.JTextArea poleWiadPowitalna;
    private javax.swing.JButton przyciskAnuluj;
    private javax.swing.JLabel textMinimalizuj;
    private javax.swing.JLabel textNaglowek;
    private javax.swing.JLabel textNazwaFirmy;
    private javax.swing.JLabel textNazwaSkrot;
    private javax.swing.JLabel textNazwaSys;
    private javax.swing.JLabel textOgloszenie;
    private javax.swing.JLabel textStopkaL;
    private javax.swing.JLabel textStopkaP;
    private javax.swing.JLabel textWWW;
    private javax.swing.JLabel textWersjaSys;
    private javax.swing.JLabel textWiadPowitalna;
    private javax.swing.JLabel textWyjscie;
    // End of variables declaration//GEN-END:variables
}
